dist: bionic
language: generic
os: 
  - windows
  - linux

addons:
  apt:
    packages:
      - python3
      - libboost-thread-dev
      - libboost-system-dev
      - ldc
      - ninja-build

compiler:
  - clang++


before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install ninja; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install ldc; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3; fi
  
script:
  - git clone https://github.com/mesonbuild/meson.git meson --branch 0.53.0 --single-branch
  - ./meson/meson.py build
  - ninja -C build
  - ninja -C build test